title: Dua For Life
description : A Website aimed to provide the importance of Dua in Everyone of our Lives
url: http://en.duaforlife.com



include: ['_includes']
categories: [home, etiquette, stories, fortress,supplications]
permalink: pretty
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

prose:
  rooturl: ''
  siteurl: 'en.duaforlife.com/'
  media: 'assets'
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "post"
      - name: "date"
        field:
          label: "date"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          label: "author"
          element: "text"
          value: "Hywel"
      - name: "categories"
        field:
          label: "categories"
          element: "text"
          placeholder: "Enter categories"
      - name: "excerpt"
        field:
          label: "excerpt"
          element: "text"
          placeholder: "Enter excerpt"
      - name: "meta"
        field:
          label: "meta"
          element: "text"
          placeholder: "Enter metadata"
  