title: Dua For Life
description : A Website aimed to provide the importance of Dua in Everyone of our Lives
url: http://en.duaforlife.com



include: ['_includes']
categories: [home, etiquette, stories, fortress,supplications]
permalink: pretty
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

## prose.io config
prose:
  rooturl: 'supplications'
  siteurl: 'http://en.duaforlife.com'
metadata:
    _/supplications:
      - name: "layout"
        field:
          element: "text"
          value: "allpages"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "description"
        field:
          element: "textarea"
          label: "description"
          placeholder: "A description of your post."
          alterable: true
      - name: "order"
        field:
          element: "text"
          label: "order"
          placeholder: "order number"
          alterable: true
      - name: "categories"
        field:
          element: "textarea"
          label: "categories"
          help: "Check to publish post, uncheck to hide."
          alterable: true
