title: Dua For Life
description : A Website aimed to provide the importance of Dua in Everyone of our Lives
url: http://en.duaforlife.com



include: ['_includes']
categories: [home, etiquette, stories, fortress,supplications]
permalink: pretty
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

prose:
  rooturl: '_posts'
  siteurl: 'en.duaforlife.com/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          value: "allpages"
      - name: "title"
        field:
          field:
          element: "text"
      - name: "description"
        field:
          field:
          element: "text"
   	  - name: "order"
        field:
          field:
          element: "text"
      - name: "category"
        field:
          field:
          element: "text"