title: Dua For Life
description : A Website aimed to provide the importance of Dua in Everyone of our Lives
url: http://en.duaforlife.com



include: ['_includes']
categories: [home, etiquette, stories, fortress,supplications]
permalink: pretty
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

prose:
  rooturl: ''
  siteurl: 'en.duaforlife.com/'
  metadata:
   supplications/fortress/content:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "allpages"
      - name: "categories"
        field:
          label: "categories"
          element: "text"
          value: "fortress"
      - name: "title"
        field:
          label: "title"
          element: "text"
          placeholder: "Enter title"
      - name: "description"
        field:
          label: "description"
          element: "text"
          placeholder: "Enter description"
      - name: "order"
        field:
          label: "order"
          element: "text"
          placeholder: "Enter order"
