title: Dua For Life
description : A Website aimed to provide the importance of Dua in Everyone of our Lives
url: http://en.duaforlife.com



include: ['_includes']
categories: [home, etiquette, stories, fortress,supplications]
permalink: pretty
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

prose:
  rooturl: 'supplications'
  siteurl: 'en.duaforlife.com/'
  metadata:
    supplications:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""