title: Dua For Life
description : A Website aimed to provide the importance of Dua in Everyone of our Lives
url: http://en.duaforlife.com



include: ['_includes']
categories: [home, etiquette, stories, fortress,supplications]
permalink: pretty
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

prose:
metadata:
 supplications:
  - name: "layout"
    field:
      element: "text"
      type: "text"
